version: '3'
services:
    wordpress:
        image: 'wordpress:latest'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WORDPRESS_DB_HOST: 'mysql:3306'
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: wordpress_password
            WORDPRESS_DB_NAME: wordpress_db
        volumes:
            - './wordpress:/var/www/html'
            - './data/uploads:/var/www/html/wp-content/uploads'
            - './config/my-php.ini:/usr/local/etc/php/conf.d/my-php.ini'
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - './data/mysql:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: wordpress_password
